#pragma once

#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"Contra (NES) testing"
#define WINDOW_ICON_PATH L"icon.ico"


#define BACKGROUND_COLOR D3DXCOLOR(0.0f/255, 0.0f/255, 0.0f/255, 255.0f/255)

#define SCREEN_WIDTH 408
#define SCREEN_HEIGHT 272
#define LEVEL_LENGTH 3320

#define ID_TEX_BILL 0
#define ID_TEX_LANCE 2
#define ID_TEX_MISC 10
#define ID_TEX_GREEDER 20
#define ID_TEX_MAP_STAGE_1 30
#define ID_TEX_TITLE 40
 
//toa do O doi xuong duoi ben trai - the gioi thuc, ko su dung ground_y khi co collision
//chi xai O tren trai cho ham ve/draw - the gioi ao
#define GROUND_Y 140.0f

#define TEXTURES_DIR L"textures"
#define TEXTURE_PATH_BILL TEXTURES_DIR "\\BillSprites.png"
#define TEXTURE_PATH_LANCE TEXTURES_DIR "\\LanceSprites.png"
#define TEXTURE_PATH_ENEMIES TEXTURES_DIR "\\Enemies.png"
#define TEXTURE_PATH_MISC TEXTURES_DIR "\\Misc.png"
#define TEXTURE_PATH_STAGE_1_MAP TEXTURES_DIR "\\Stage1Map.png"
#define TEXTURE_PATH_BBOX TEXTURES_DIR "\\bbox.png"
#define TEXTURE_PATH_TITLE TEXTURES_DIR "\\Menu.png"

//keyboard stuff
#define ON_KEY_UP 1
#define ON_KEY_DOWN 2
#define KEY_STATE 3

//LAND AND SKY STUFF

#define ID_ANI_LAND_0 2000
#define ID_ANI_LAND_1 2001
#define ID_ANI_LAND_2 2002
#define ID_ANI_LAND_3 2003
#define ID_ANI_LAND_4 2004
#define ID_ANI_LAND_5 2005
#define LAND_WIDTH 24.0f

#define ID_ANI_STAGE_1_0 3000
#define MAP_TILE_WIDTH 32.0f

 //BILL STUFF

#define BILL_WIDTH 22.0f
#define BILL_HEIGHT 40.0f

#define BILL_START_X 30.0f
#define BILL_START_Y GROUND_Y + 50.0f

#define BILL_WALK_SPEED		0.1f

#define BILL_JUMP_SPEED_Y		0.45f

#define BILL_GRAVITY			0.0018f



#define BILL_STATE_IDLE			000

#define BILL_STATE_WALK	100

#define BILL_STATE_WALK_LOOK_UP	110

#define BILL_STATE_WALK_LOOK_DOWN 120

#define BILL_STATE_JUMP			130

#define BILL_STATE_RELEASE_JUMP    140

#define BILL_STATE_SIT			150

#define BILL_STATE_LOOK_UP		160



#define ID_ANI_BILL_IDLE_RIGHT 0000
#define ID_ANI_BILL_IDLE_LEFT 0001

#define ID_ANI_BILL_WALK_RIGHT 1000
#define ID_ANI_BILL_WALK_LEFT 1001

#define ID_ANI_BILL_WALK_LOOK_UP_RIGHT 1100
#define ID_ANI_BILL_WALK_LOOK_UP_LEFT 1101

#define ID_ANI_BILL_WALK_LOOK_DOWN_RIGHT 1200
#define ID_ANI_BILL_WALK_LOOK_DOWN_LEFT 1201

#define ID_ANI_BILL_JUMP_RIGHT 1300
#define ID_ANI_BILL_JUMP_LEFT 1301

#define ID_ANI_BILL_SIT_RIGHT 1500
#define ID_ANI_BILL_SIT_LEFT 1501

#define ID_ANI_BILL_LOOK_UP_RIGHT 1600
#define ID_ANI_BILL_LOOK_UP_LEFT 1601

//LANCE STUFF

#define LANCE_WIDTH 40.0f
#define LANCE_HEIGHT 40.0f

#define LANCE_START_X 30.0f
#define LANCE_START_Y GROUND_Y + 50.0f

#define LANCE_WALK_SPEED		0.05f
#define LANCE_RUNNING_SPEED		0.1f

#define LANCE_JUMP_SPEED_Y		0.45f

#define LANCE_GRAVITY			0.0018f



#define LANCE_STATE_IDLE			000

#define LANCE_STATE_WALK	100

#define LANCE_STATE_WALK_LOOK_UP	110

#define LANCE_STATE_WALK_LOOK_DOWN 120

#define LANCE_STATE_JUMP			130

#define LANCE_STATE_RELEASE_JUMP    140

#define LANCE_STATE_SIT			150

#define LANCE_STATE_LOOK_UP		160



#define ID_ANI_LANCE_IDLE_RIGHT 4000
#define ID_ANI_LANCE_IDLE_LEFT 4001

#define ID_ANI_LANCE_WALK_RIGHT 5000
#define ID_ANI_LANCE_WALK_LEFT 5001

#define ID_ANI_LANCE_WALK_LOOK_UP_RIGHT 5100
#define ID_ANI_LANCE_WALK_LOOK_UP_LEFT 5101

#define ID_ANI_LANCE_WALK_LOOK_DOWN_RIGHT 5200
#define ID_ANI_LANCE_WALK_LOOK_DOWN_LEFT 5201

#define ID_ANI_LANCE_JUMP_RIGHT 5300
#define ID_ANI_LANCE_JUMP_LEFT 5301

#define ID_ANI_LANCE_SIT_RIGHT 5500
#define ID_ANI_LANCE_SIT_LEFT 5501

#define ID_ANI_LANCE_LOOK_UP_RIGHT 5600
#define ID_ANI_LANCE_LOOK_UP_LEFT 5601


// GREEDER STUFF

#define GREEDER_WIDTH 22.0f
#define GREEDER_HEIGHT 40.0f

#define GREEDER_START_X 50.0f
#define GREEDER_START_Y GROUND_Y

#define ID_ANI_GREEDER_RUN_LEFT 20010
#define ID_ANI_GREEDER_RUN_RIGHT 20020

#define GREEDER_RUNNING_SPEED		0.15f

//TITLE STUFF

#define TITLE_WIDTH 194.0f
#define TITLE_HEIGHT 207.0f

#define TITLE_START_X SCREEN_WIDTH
#define TITLE_START_Y GROUND_Y - 20.0f

#define ID_ANI_TITLE_RUN_RIGHT 40040

#define TITLE_SPEED		0.1f

#define MENU1_WIDTH 65.0f
#define MENU1_HEIGHT 7.0f

#define MENU1_START_X TITLE_WIDTH/2 + 60
#define MENU1_START_Y TITLE_HEIGHT/2 - 25

#define ID_MENU1 40010

#define MENU2_WIDTH 65.0f
#define MENU2_HEIGHT 7.0f

#define MENU2_START_X TITLE_WIDTH/2 + 65
#define MENU2_START_Y TITLE_HEIGHT/2 - 40

#define ID_MENU2 40020

#define BADGE_WIDTH 15.0f
#define BADGE_HEIGHT 9.0f

#define BADGE_START_X TITLE_WIDTH/2 + 15
#define BADGE_START_Y TITLE_HEIGHT/2 - 24

#define BADGE_SECOND_X TITLE_WIDTH/2 + 15
#define BADGE_SECOND_Y TITLE_HEIGHT/2 - 40

#define ID_BADGE 40030