#pragma once

#include "MapRead.h"

extern Stage* stage1;

#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"Contra (NES) testing"
#define WINDOW_ICON_PATH L"icon.ico"

#define BACKGROUND_COLOR D3DXCOLOR(0.0f/255, 0.0f/255, 0.0f/255, 0.0f)

#define SCREEN_WIDTH stage1->ScreenWidth
#define SCREEN_HEIGHT stage1->ScreenHeight
#define LEVEL_LENGTH stage1->LevelLength

#define ID_TEX_BILL 0
#define ID_TEX_LANCE 2
#define ID_TEX_MISC 10
#define ID_TEX_GREEDER 20
#define ID_TEX_MAP_STAGE_1 30
#define ID_TEX_TITLE 40
#define ID_TEX_BULLET 100

#define TEXTURES_DIR L"textures"
#define TEXTURE_PATH_BILL TEXTURES_DIR "\\BillSprites.png"
#define TEXTURE_PATH_LANCE TEXTURES_DIR "\\LanceSprites.png"
#define TEXTURE_PATH_ENEMIES TEXTURES_DIR "\\Enemies.png"
#define TEXTURE_PATH_MISC TEXTURES_DIR "\\Misc.png"
#define TEXTURE_PATH_STAGE_1_MAP TEXTURES_DIR "\\Stage1Map.png"
#define TEXTURE_PATH_BBOX TEXTURES_DIR "\\bbox.png"
#define TEXTURE_PATH_TITLE TEXTURES_DIR "\\Menu.png"

//keyboard stuff
#define ON_KEY_UP 1
#define ON_KEY_DOWN 2
#define KEY_STATE 3

//LAND AND SKY STUFF
#define LAND_WIDTH 24.0f

#define ID_ANI_STAGE_1_0 3000
#define MAP_TILE_WIDTH 32.0f

//BULLET STUFF
#define ID_ANI_BULLET 9000
 //BILL STUFF

#define BILL_COOLDOWN 15
#define BILL_START_X stage1->Billx
#define BILL_START_Y stage1->Billy
#define BILL_WIDTH 15.0f
#define BILL_HEIGHT 20.0f
#define BILL_WALK_SPEED		0.1f
#define BILL_JUMP_SPEED_Y		0.5f
#define GAME_GRAVITY			0.002f
#define BILL_STATE_IDLE			000//
#define BILL_STATE_DIE 010
#define BILL_STATE_WALK	100//
#define BILL_STATE_WALK_LOOK_UP	110
#define BILL_STATE_WALK_LOOK_DOWN 120
#define BILL_STATE_JUMP			130
#define BILL_STATE_FALL    140
#define BILL_STATE_SIT			150
#define BILL_STATE_LOOK_UP		160
#define BILL_STATE_SWIM_IDLE 200
#define BILL_STATE_SWIM_WALK 300
#define BILL_STATE_SWIM_SIT 350

#define ID_ANI_BILL_IDLE_RIGHT 0000
#define ID_ANI_BILL_IDLE_LEFT 0001
#define ID_ANI_BILL_IDLE_RIGHT_SHOOT 0020
#define ID_ANI_BILL_IDLE_LEFT_SHOOT 0021

#define ID_ANI_BILL_WALK_RIGHT 1000
#define ID_ANI_BILL_WALK_LEFT 1001
#define ID_ANI_BILL_WALK_RIGHT_SHOOT 1020
#define ID_ANI_BILL_WALK_LEFT_SHOOT 1021

#define ID_ANI_BILL_WALK_LOOK_UP_RIGHT 1100
#define ID_ANI_BILL_WALK_LOOK_UP_LEFT 1101
#define ID_ANI_BILL_WALK_LOOK_UP_RIGHT_SHOOT 1120
#define ID_ANI_BILL_WALK_LOOK_UP_LEFT_SHOOT 1121

#define ID_ANI_BILL_WALK_LOOK_DOWN_RIGHT 1200
#define ID_ANI_BILL_WALK_LOOK_DOWN_LEFT 1201
#define ID_ANI_BILL_WALK_LOOK_DOWN_RIGHT_SHOOT 1220
#define ID_ANI_BILL_WALK_LOOK_DOWN_LEFT_SHOOT 1221

#define ID_ANI_BILL_JUMP_RIGHT 1300
#define ID_ANI_BILL_JUMP_LEFT 1301

#define ID_ANI_BILL_SIT_RIGHT 1500
#define ID_ANI_BILL_SIT_LEFT 1501
#define ID_ANI_BILL_SIT_RIGHT_SHOOT 1520
#define ID_ANI_BILL_SIT_LEFT_SHOOT 1521

#define ID_ANI_BILL_LOOK_UP_RIGHT 1600
#define ID_ANI_BILL_LOOK_UP_LEFT 1601
#define ID_ANI_BILL_LOOK_UP_RIGHT_SHOOT 1620
#define ID_ANI_BILL_LOOK_UP_LEFT_SHOOT 1621

#define ID_ANI_BILL_SWIM_RIGHT 1700
#define ID_ANI_BILL_SWIM_LEFT 1701
#define ID_ANI_BILL_SWIM_UNDER 1702
#define ID_ANI_BILL_SWIM_RIGHT_SHOOT 1720
#define ID_ANI_BILL_SWIM_LEFT_SHOOT 17221
//LANCE STUFF

#define LANCE_START_X stage1->Lancex
#define LANCE_START_Y stage1->Lancey

#define ID_ANI_LANCE_IDLE_RIGHT 4000
#define ID_ANI_LANCE_IDLE_LEFT 4001

#define ID_ANI_LANCE_WALK_RIGHT 5000
#define ID_ANI_LANCE_WALK_LEFT 5001

#define ID_ANI_LANCE_WALK_LOOK_UP_RIGHT 5100
#define ID_ANI_LANCE_WALK_LOOK_UP_LEFT 5101

#define ID_ANI_LANCE_WALK_LOOK_DOWN_RIGHT 5200
#define ID_ANI_LANCE_WALK_LOOK_DOWN_LEFT 5201

#define ID_ANI_LANCE_JUMP_RIGHT 5300
#define ID_ANI_LANCE_JUMP_LEFT 5301

#define ID_ANI_LANCE_SIT_RIGHT 5500
#define ID_ANI_LANCE_SIT_LEFT 5501

#define ID_ANI_LANCE_LOOK_UP_RIGHT 5600
#define ID_ANI_LANCE_LOOK_UP_LEFT 5601


 // GREEDER STUFF

#define GREEDER_WIDTH 15.0f
#define GREEDER_HEIGHT 20.0f

#define GREEDER_START_X 100.0f
#define GREEDER_START_Y 200.0f

#define ID_ANI_GREEDER_RUN_LEFT 20010
#define ID_ANI_GREEDER_RUN_RIGHT 20020

#define GREEDER_RUNNING_SPEED		0.101f
 
 //TITLE STUFF

#define TITLE_WIDTH 194.0f
#define TITLE_HEIGHT 207.0f

#define TITLE_START_X SCREEN_WIDTH
#define TITLE_START_Y 120.0f

#define ID_ANI_TITLE_RUN_RIGHT 40040

#define TITLE_SPEED		0.1f

#define MENU1_WIDTH 65.0f
#define MENU1_HEIGHT 7.0f

#define MENU1_START_X TITLE_WIDTH/2 + 60
#define MENU1_START_Y TITLE_HEIGHT/2 - 25

#define ID_MENU1 40010

#define MENU2_WIDTH 65.0f
#define MENU2_HEIGHT 7.0f

#define MENU2_START_X TITLE_WIDTH/2 + 65
#define MENU2_START_Y TITLE_HEIGHT/2 - 40

#define ID_MENU2 40020

#define BADGE_WIDTH 15.0f
#define BADGE_HEIGHT 9.0f

#define BADGE_START_X TITLE_WIDTH/2 + 15
#define BADGE_START_Y TITLE_HEIGHT/2 - 24

#define BADGE_SECOND_X TITLE_WIDTH/2 + 15
#define BADGE_SECOND_Y TITLE_HEIGHT/2 - 40

#define ID_BADGE 40030